name: flutter_rtmp
description: Controlling the camera on Android and iOS plus rtmp live streaming support. Based off the Camera plugin.
version: 0.3.3
homepage: https://github.com/turbatdd/flutter_rtmp

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^2.0.1
  video_player: ^2.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.11.0
  mockito: ^5.0.7
  flutter_lints: ^1.0.0

dependency_overrides:
  crypto: ^3.0.1
  convert: ^3.0.1

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.turbatdd.flutter_rtmp
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: RtmppublisherPlugin